// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrwyztjgcpnhuzkvkmoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyd3l6dGpnY3BuaHV6a3ZrbW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjgwMTAsImV4cCI6MjA3MDc0NDAxMH0.KKcSwlUiOG54aNpZI1Ga4ZwyyWkzWTxdMQdbM41GglQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});